spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
          google:
            client-id: 936183283854-jhn2dj4ib9f90cimv74uitm2097mkutn.apps.googleusercontent.com
            client-secret: iRDNZScKIO2FGKzAypq9dQef
        provider:          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v1/token
            user-info-uri: https://www.googleapis.com/userinfo/v2/me
            user-name-attribute: sub
            jwk-set-uri: https://www-googleapis.com/oauth2/v1/keys